### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by ryanpcmcquen** [ryanolsonx/sublimetext-zenburn-theme#1]
Thanks for bringing this to Sublime Text, the other 'Zenburn' has some piercing colors that I'm pretty sure were created to singe your eyeballs.

Have you considered changing the description for this on Package Control? The current description made me think this was just a straight port, rather than a lovingly cared for, crafted, artisan, and maintained Zenburn for Sublime.

**Comment by ryanolsonx** [comment]
You're welcome! Thanks for the compliments.

You're right. I can probably improve the wording for the description of this package. As it stands, what's probably missing is that this is a TRUE port of the original Zenburn theme. The other one isn't _really_ Zenburn.

**Comment by ryanpcmcquen** [comment]
"It is truly Zen."

**Comment by ryanolsonx** [comment]
Changed to "Hand-crafted port of Zenburn from Vim. Zenburn is a low-contrast color scheme designed to be easy on your eyes. Embrace the Zen."

It should show up in package control once it does its next update of packages (I think it does that every 30 min).

Does that seem like a better description?

**Comment by ryanpcmcquen** [comment]
Definitely! It's funny because I installed the other one first based on the description, but I think this new description would have changed my past behavior.

Thanks again!

**Comment by ryanolsonx** [comment]
Thanks!!
